require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssignmentsController do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # update the return value of this method accordingly.
  def valid_attributes 
    FactoryGirl.attributes_for(:assignment)
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # usersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns assignments as @assignment" do
      Assignment.any_instance.stubs(:valid?).returns(true)
      assignment = FactoryGirl.create :associated_assignment
      get :index, {}, valid_session
      assigns(:assignments).should eq([assignment])
    end
    
    it "only assigns most recent assign_date per computer_id to @assignment" do
      Assignment.any_instance.stubs(:valid?).returns(true)
      2.times { FactoryGirl.create(:assignment) }
      FactoryGirl.create(:computer, id: 1)
      get :index, {}, valid_session
      assigns(:assignments).should have(1).Assignment
    end

    it "assigns 2 computer_id to @assignment for different ids" do
      pending ("Issues with Associations") do
      Assignment.any_instance.stubs(:valid?).returns(true)
      2.times { 
        FactoryGirl.create(:associated_assignment)
        FactoryGirl.create(:dummy_assignment)
      }
      get :index, {}, valid_session
      assigns(:assignments).should have(2).Assignment
      end
    end

  end

  describe "GET show" do
    it "assigns the requested assignment as @assignment" do
      Assignment.any_instance.stubs(:valid?).returns(true)
      assignment = Assignment.create! valid_attributes
      get :show, {:id => assignment.to_param}, valid_session
      assigns(:assignment).should eq(assignment)
    end
  end

  describe "POST new" do
    #WIP
    #it "assigns a new assignment as @assignment" do
    #  User.any_instance.stubs(:valid?).returns(true)
    #  get :new, {}, valid_session
    #  assigns(:user).should be_a_new(User)
    #end
    
    #WIP
    it "fails if assign_date is already taken" do
    end
  end

  describe "GET edit" do
    it "assigns the requested assignment as @assignment" do
      Assignment.any_instance.stubs(:valid?).returns(true)
      assignment = Assignment.create! valid_attributes
      get :edit, {:id => assignment.to_param}, valid_session
      assigns(:assignment).should eq(assignment)
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assignment" do
        assignment = Assignment.create! valid_attributes
        # Assuming there are no other users in the database, this
        # specifies that the User created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Assignment.any_instance.expects(:update_attributes).with({'these' => 'params'})
        put :update, {:id => assignment.to_param, :assignment => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested assignment as @assignment" do
        assignment = Assignment.create! valid_attributes
        put :update, {:id => assignment.to_param, :assignment => valid_attributes}, valid_session
        assigns(:assignment).should eq(assignment)
      end

      it "redirects to the assignment" do
        assignment = Assignment.create! valid_attributes
        put :update, {:id => assignment.to_param, :assignment => valid_attributes}, valid_session
        response.should redirect_to(assignment)
      end
    end

    describe "with invalid params" do
      it "assigns the assignment as @assignment" do
        assignment = Assignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Assignment.any_instance.stubs(:save).returns(false)
        put :update, {:id => assignment.to_param, :assignment => {}}, valid_session
        assigns(:assignment).should eq(assignment)
      end

      it "re-renders the 'edit' template" do
        assignment = Assignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Assignment.any_instance.stubs(:save).returns(false)
        put :update, {:id => assignment.to_param, :assignment => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user" do
      assignment = Assignment.create! valid_attributes
      expect {
        delete :destroy, {:id => assignment.to_param}, valid_session
      }.to change(Assignment, :count).by(-1)
    end

    it "redirects to the users list" do
      assignment = Assignment.create! valid_attributes
      delete :destroy, {:id => assignment.to_param}, valid_session
      response.should redirect_to(assignments_url)
    end
  end

  describe "GET history" do
    it "assigns all assignments to @assignments" do
      Assignment.any_instance.stubs(:valid?).returns(true)
      assignment = Assignment.create! valid_attributes
      get :history, {}, valid_session
      assigns(:assignments).should eq([assignment])
    end
  end

  describe "PUT report" do

    #fname tests
    describe "with matching FNAME" do
      it "assigns assignments which user_id's fname match to @assignments" do
        assignment = FactoryGirl.create :associated_assignment
        put :report, {:fname => 'John',
                      :lname => '',
                      :start_date => '',
                      :end_date => ''
        }, valid_session
        assigns(:assignments).should eq([assignment])
      end
    end

    describe "with non-matching FNAME" do
      it "assigns nothing" do
        assignment = FactoryGirl.create :associated_assignment
        put :report, {:fname => 'Robert',
                      :lname => '',
                      :start_date => '',
                      :end_date => ''
        }, valid_session
        assigns(:assignments).should have(0).Assignment
      end
    end

    describe "with partial match on FNAME" do
      it "assigns assignments which user_id's fname match to @assignments" do
        assignment = FactoryGirl.create :associated_assignment
        put :report, {:fname => 'Jo',
                      :lname => '',
                      :start_date => '',
                      :end_date => ''
        }, valid_session
        pending("Code not implemented") do
          assigns(:assignments).should eq([assignment])
        end
      end
    end
    
    #lname tests
    describe "with LNAME" do
      it "matching assigns lname-matched @assignments" do
        assignment = FactoryGirl.create :associated_assignment
                    put :report, {:fname => '',
                    :lname => 'Smith',
                    :start_date => '',
                    :end_date => ''
        }, valid_session
        assigns(:assignments).should eq([assignment])
      end

      it "not matching assigns nothing" do
        assignment = FactoryGirl.create :associated_assignment
                   put :report, {:fname => '',
                   :lname => 'Greens',
                   :start_date => '',
                   :end_date => ''
          }, valid_session
          assigns(:assignments).should have(0).Assignment
      end

      it "partially matching assigns lname-matched @assignments" do
        assignment = FactoryGirl.create :associated_assignment
                   put :report, {:fname => '',
                   :lname => 'Sm',
                   :start_date => '',
                   :end_date => ''
        }, valid_session
        pending("Code not implemented") do
          assigns(:assignments).should eq([assignment])
        end
      end
    end

    #start_date tests
    describe "with start_date" do
      it "returns assignment dates matching" do
        assignment = FactoryGirl.create :associated_assignment
                  put :report, {:fname => '',
                  :lname => '',
                  :start_date => '11-11-2008',
                  :end_date => ''
         }, valid_session
         assigns(:assignments).should eq([assignment])
      end

      it "returns assignments dates after" do
        assignment = FactoryGirl.create :associated_assignment
                  put :report, {:fname => '',
                  :lname => '',
                  :start_date => '11-11-2007',
                  :end_date => ''
         }, valid_session
         assigns(:assignments).should eq([assignment])
      end

      it "returns no assignments dates before" do
        assignment = FactoryGirl.create :associated_assignment
                  put :report, {:fname => '',
                  :lname => '',
                  :start_date => '11-11-2009',
                  :end_date => ''
         }, valid_session
         assigns(:assignments).should have(0).Assignment
      end
    end

    #end_date tests
    describe "with end_date" do
      it "returns assignment dates matching" do
        assignment = FactoryGirl.create :associated_assignment
                  put :report, {:fname => '',
                  :lname => '',
                  :start_date => '',
                  :end_date => '11-11-2008'
         }, valid_session
         assigns(:assignments).should eq([assignment])
      end

      it "returns assignments dates before" do
        assignment = FactoryGirl.create :associated_assignment
                  put :report, {:fname => '',
                  :lname => '',
                  :start_date => '',
                  :end_date => '11-11-2009'
         }, valid_session
         assigns(:assignments).should eq([assignment])
      end

      it "returns no assignments dates after" do
        assignment = FactoryGirl.create :associated_assignment
                  put :report, {:fname => '',
                  :lname => '',
                  :start_date => '',
                  :end_date => '11-11-2007'
         }, valid_session
         assigns(:assignments).should have(0).Assignment
      end
    end

    #date range tests
    describe "with start_date AND end_date" do
      it "returns assignment dates matching" do
        assignment = FactoryGirl.create :associated_assignment
                  put :report, {:fname => '',
                  :lname => '',
                  :start_date => '11-11-2008',
                  :end_date => '11-11-2008'
         }, valid_session
         assigns(:assignments).should eq([assignment])
      end

      it "returns assignments dates inside range" do
        assignment = FactoryGirl.create :associated_assignment
                  put :report, {:fname => '',
                  :lname => '',
                  :start_date => '11-11-2007',
                  :end_date => '11-11-2009'
         }, valid_session
         assigns(:assignments).should eq([assignment])
      end

      it "returns no assignments before range" do
        assignment = FactoryGirl.create :associated_assignment
                  put :report, {:fname => '',
                  :lname => '',
                  :start_date => '11-11-2009',
                  :end_date => '11-11-2010'
         }, valid_session
         assigns(:assignments).should have(0).Assignment
      end
      
      it "returns no assignments after range" do
        assignment = FactoryGirl.create :associated_assignment
                  put :report, {:fname => '',
                  :lname => '',
                  :start_date => '11-11-2006',
                  :end_date => '11-11-2007'
         }, valid_session
         assigns(:assignments).should have(0).Assignment
      end
    end

    describe "with empty form" do
      it "re-renders 'report' template with error" do
        assignment = FactoryGirl.create :associated_assignment
                  put :report, {:fname => '',
                  :lname => '',
                  :start_date => '',
                  :end_date => ''
        }, valid_session
        response.should redirect_to("/assignments/report_query")
      end
    end
  end #End PUT Report
end
